insert into pn_member values ('pnut1', '11111','유저1','피넛유저1','k1@k.com','010-1111-1111','#한식 #김치찌개',sysdate,'n','profile1.jpg','default.jpg');
insert into pn_member values ('pnut2', '11111','유저2','피넛유저2','k1@k.com','010-1111-1111','#일식 #초밥',sysdate,'n','profile2.jpg','default.jpg');
insert into pn_member values ('pnut3', '11111','유저3','피넛유저3','k1@k.com','010-1111-1111','#중식 #짜장면',sysdate,'n','profile3.jpg','default.jpg');
insert into pn_member values ('pnut4', '11111','유저4','피넛유저4','k1@k.com','010-1111-1111','#양식 #까르보나라',sysdate,'n','profile4.jpg','default.jpg');
insert into pn_member values ('pnut5', '11111','유저5','피넛유저5','k1@k.com','010-1111-1111','#한식 #쌈밥',sysdate,'n','profile5.jpg','default.jpg');
insert into pn_member values ('pnut6', '11111','유저6','피넛유저6','k1@k.com','010-1111-1111','#일식 #라멘',sysdate,'n','profile6.jpg','default.jpg');
insert into pn_member values ('pnut7', '11111','유저7','피넛유저7','k1@k.com','010-1111-1111','#중식 #마파두부',sysdate,'n','profile7.jpg','default.jpg');
insert into pn_member values ('pnut8', '11111','유저8','피넛유저8','k1@k.com','010-1111-1111','#양식 #피자',sysdate,'n','profile8.jpg','default.jpg');
insert into pn_member values ('pnut9', '11111','유저9','피넛유저9','k1@k.com','010-1111-1111','#한식 #불고기',sysdate,'n','profile9.jpg','default.jpg');
insert into pn_member values ('pnut10', '11111','유저10','피넛유저10','k1@k.com','010-1111-1111','#일식 #우동',sysdate,'n','profile10.jpg','default.jpg');

insert into pn_member values ('pnut11', '11111','유저11','피넛유저11','k1@k.com','010-1111-1111','#중식 #짬뽕',sysdate,'n','profile11.jpg','default.jpg');
insert into pn_member values ('pnut12', '11111','유저12','피넛유저12','k1@k.com','010-1111-1111','#양식 #리조또',sysdate,'n','profile12.jpg','default.jpg');
insert into pn_member values ('pnut13', '11111','유저13','피넛유저13','k1@k.com','010-1111-1111','#야식 #족발',sysdate,'n','profile13.jpg','default.jpg');
insert into pn_member values ('pnut14', '11111','유저14','피넛유저14','k1@k.com','010-1111-1111','#디저트 #마카롱',sysdate,'n','profile14.jpg','default.jpg');
insert into pn_member values ('pnut15', '11111','유저15','피넛유저15','k1@k.com','010-1111-1111','#한식 #비빔밥',sysdate,'n','profile15.jpg','default.jpg');
insert into pn_member values ('pnut16', '11111','유저16','피넛유저16','k1@k.com','010-1111-1111','#일식 #오니기리',sysdate,'n','profile16.jpg','default.jpg');
insert into pn_member values ('pnut17', '11111','유저17','피넛유저17','k1@k.com','010-1111-1111','#중식 #양장피',sysdate,'n','profile17.jpg','default.jpg');
insert into pn_member values ('pnut18', '11111','유저18','피넛유저18','k1@k.com','010-1111-1111','#양식 #봉골레',sysdate,'n','profile18.jpg','default.jpg');
insert into pn_member values ('pnut19', '11111','유저19','피넛유저19','k1@k.com','010-1111-1111','#야식 #치킨',sysdate,'n','profile19.jpg','default.jpg');
insert into pn_member values ('pnut20', '11111','유저20','피넛유저20','k1@k.com','010-1111-1111','#디저트 #푸딩',sysdate,'n','profile20.jpg','default.jpg');

insert into pn_member values ('pnut21', '11111','유저21','피넛유저21','k1@k.com','010-1111-1111','#한식 #부대찌개',sysdate,'n','profile21.jpg','default.jpg');
insert into pn_member values ('pnut22', '11111','유저22','피넛유저22','k1@k.com','010-1111-1111','#일식 #사시미',sysdate,'n','profile22.jpg','default.jpg');
insert into pn_member values ('pnut23', '11111','유저23','피넛유저23','k1@k.com','010-1111-1111','#중식 #탕수육',sysdate,'n','profile23.jpg','default.jpg');
insert into pn_member values ('pnut24', '11111','유저24','피넛유저24','k1@k.com','010-1111-1111','#양식 #비프스튜',sysdate,'n','profile24.jpg','default.jpg');
insert into pn_member values ('pnut25', '11111','유저25','피넛유저25','k1@k.com','010-1111-1111','#해장 #콩나물국밥',sysdate,'n','profile25.jpg','default.jpg');
insert into pn_member values ('pnut26', '11111','유저26','피넛유저26','k1@k.com','010-1111-1111','#분식 #김밥',sysdate,'n','profile26.jpg','default.jpg');
insert into pn_member values ('pnut27', '11111','유저27','피넛유저27','k1@k.com','010-1111-1111','#한식 #간장게장',sysdate,'n','profile27.jpg','default.jpg');
insert into pn_member values ('pnut28', '11111','유저28','피넛유저28','k1@k.com','010-1111-1111','#일식 #소바',sysdate,'n','profile28.jpg','default.jpg');
insert into pn_member values ('pnut29', '11111','유저29','피넛유저29','k1@k.com','010-1111-1111','#중식 #유린기',sysdate,'n','profile29.jpg','default.jpg');
insert into pn_member values ('pnut30', '11111','유저30','피넛유저30','k1@k.com','010-1111-1111','#양식 #햄버거',sysdate,'n','profile30.jpg','default.jpg');

insert into pn_member values ('pnut31', '11111','유저31','피넛유저31','k1@k.com','010-1111-1111','#분식 #떡볶이',sysdate,'n','profile31.jpg','default.jpg');
insert into pn_member values ('pnut32', '11111','유저32','피넛유저32','k1@k.com','010-1111-1111','#해장 #뼈해장국',sysdate,'n','profile32.jpg','default.jpg');
insert into pn_member values ('pnut33', '11111','유저33','피넛유저33','k1@k.com','010-1111-1111','#한식 #순두부찌개',sysdate,'n','profile33.jpg','default.jpg');
insert into pn_member values ('pnut34', '11111','유저34','피넛유저34','k1@k.com','010-1111-1111','#일식 #돈카츠',sysdate,'n','profile34.jpg','default.jpg');
insert into pn_member values ('pnut35', '11111','유저35','피넛유저35','k1@k.com','010-1111-1111','#중식 #고추잡채',sysdate,'n','profile35.jpg','default.jpg');
insert into pn_member values ('pnut36', '11111','유저36','피넛유저36','k1@k.com','010-1111-1111','#양식 #브리또',sysdate,'n','profile36.png','default.jpg');
insert into pn_member values ('pnut37', '11111','유저37','피넛유저37','k1@k.com','010-1111-1111','#야식 #보쌈',sysdate,'n','profile37.png','default.jpg');
insert into pn_member values ('pnut38', '11111','유저38','피넛유저38','k1@k.com','010-1111-1111','#분식 #어묵',sysdate,'n','profile38.png','default.jpg');
insert into pn_member values ('pnut39', '11111','유저39','피넛유저39','k1@k.com','010-1111-1111','#디저트 #아이스크림',sysdate,'n','profile39.png','default.jpg');
insert into pn_member values ('pnut40', '11111','유저40','피넛유저40','k1@k.com','010-1111-1111','#해장 #우거지국',sysdate,'n','profile40.png','default.jpg');


insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut1', '#한식 #김치찌개 ㅈㅁㅌ 요즘 #민트초코 에 빠져있다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-200, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut2', '내일 #일식 #초밥 100개 먹방 도전합니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-199, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut3', '#코딩 #자바 공부 시작', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-198, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut4', '#야식 #치킨 #족발 끊을 수가 없네요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-197, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut5', '어제 너무 마셨는데 #해장 으로 뭐먹지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-196, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut6', '오늘도 고민한다 #김치찌개 #된장찌개 #순두부찌개', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-195, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut7', '#해장 엔 역시 #콩나물국밥 만한게 없지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-194, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut8', '자다가 속쓰려서 일어났다...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-193, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut9', '#안동소주 는 참 좋은게 몇잔만 마셔도 적당히 취기가 올라서 현생 스트레스 잊는데 도움이 된다. #소주는 몇 병을 마셔도 취한줄도 모르다 갑자기 훅 가버리는 느낌이야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-192, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut10', '오늘 #생일 인데 축하해주는 사람 하나 없네', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-191, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut11', '나만 #고양이 없어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-190, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut12', '끼요오오옷', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-189, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut13', '#탕수육 부먹했다고 진짜 싸울뻔했네;;', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-188, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut14', '새벽에 이게 뭐하는 짓이야 ㅋㅋ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-187, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut15', '#김밥 에 #오이 들어간 건 참을 수가 없다 대체 왜 넣는거야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-186, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut16', '#파이썬 입문중인데 꿀잼이네. 나 이쪽 적성에 맞나봐요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-185, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut17', '이 시국이 끝나야 #해외여행 도 좀 가고 할텐데...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-184, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut18', '#민트초코 그거 완전 치약맛 아닌가요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-183, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut19', '비도 오고 오늘은 #짬뽕 각이다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-182, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut20', '요즘 #햄버거 만 너무 먹어댔더니 살 쪄가는게 눈에 보이는 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-181, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut21', '#한식 #일식 #양식 뭐먹지 메뉴 정하기 너무 힘들다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-180, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut22', '#데이터베이스 공부중인데 잘 이해가 안되네요 ㅠ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-179, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut23', '어머니는 #짜장면 이 싫다고 하셨어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-178, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut24', '#스마트폰 바꿀 때 된거같은데 #아이폰 #갤럭시 고민된다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-177, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut25', '#넷플릭스 #퀸스갬빗 진짜 재밌어 #체스 하는 사람이면 꼭 봐라 두 번 봐라', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-176, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut26', '#가챠 또 폭사했다. 확률 너무 양심없는거 아닙니까', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-175, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut27', '#라멘 은 역시 #돈코츠라멘 이라 생각했는데 요즘 #츠케멘 에 눈을 뜨게 된 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-174, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut28', '#빅데이터 에 기반해 조사한 결과 당신은 지금 #치킨이 먹고싶습니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-173, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut29', '이 시간만 되면 묘한 두통이 찾아오는데 이유가 뭐지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-172, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut30', '윗집엔 #코끼리 를 키우고 있는게 분명하다 이 세상 #층간소음 이 아니다 진짜', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-171, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut31', '#ajax 배우니까 신세계가 열린 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-170, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut32', '진성 #까르보나라 덕후인 저도 가끔 #토마토파스타 가 더 땡길 때가 있긴 해요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-169, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut33', '#해장 으로 #해장술 마신다는 사람과는 거리를 좀 두는게 좋아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-168, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut34', '#마카롱 선물받은거 냉동실에 넣어놨다 까먹었어; 두 달 지났는데 이거 먹어도 될까요?', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-167, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut35', '못참겠다 #야식 주문 간다 #족발 vs #보쌈 뭐시키지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-166, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut36', '시연용 더미데이터 계획은 다 다른 문장으로 200개 만드는 거였는데 졸려서 못해먹겠다 걍 복붙해야지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-165, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut37', '#Eclipse 만 쓰다가 얼마전에 #IntelliJ 조금씩 써보고 있는데 편한 부분이 많긴 하다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-164, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut38', '벌써 새벽 네시 반이 넘었어 이젠 정말 자야해', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-163, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut39', '정말 애석하게도 내 #고양이 아니고 퍼온 사진입니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-162, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut40', '진짜 완성 못하는줄 알았는데 #프로젝트 마무리가 되긴 됐다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-161, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut1', '#한식 #김치찌개 ㅈㅁㅌ 요즘 #민트초코 에 빠져있다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-160, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut2', '내일 #일식 #초밥 100개 먹방 도전합니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-159, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut3', '#코딩 #자바 공부 시작', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-158, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut4', '#야식 #치킨 #족발 끊을 수가 없네요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-157, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut5', '어제 너무 마셨는데 #해장 으로 뭐먹지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-156, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut6', '오늘도 고민한다 #김치찌개 #된장찌개 #순두부찌개', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-155, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut7', '#해장 엔 역시 #콩나물국밥 만한게 없지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-154, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut8', '자다가 속쓰려서 일어났다...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-153, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut9', '#안동소주 는 참 좋은게 몇잔만 마셔도 적당히 취기가 올라서 현생 스트레스 잊는데 도움이 된다. #소주는 몇 병을 마셔도 취한줄도 모르다 갑자기 훅 가버리는 느낌이야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-152, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut10', '오늘 #생일 인데 축하해주는 사람 하나 없네', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-151, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut11', '나만 #고양이 없어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-150, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut12', '끼요오오옷', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-149, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut13', '#탕수육 부먹했다고 진짜 싸울뻔했네;;', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-148, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut14', '새벽에 이게 뭐하는 짓이야 ㅋㅋ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-147, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut15', '#김밥 에 #오이 들어간 건 참을 수가 없다 대체 왜 넣는거야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-146, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut16', '#파이썬 입문중인데 꿀잼이네. 나 이쪽 적성에 맞나봐요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-145, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut17', '이 시국이 끝나야 #해외여행 도 좀 가고 할텐데...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-144, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut18', '#민트초코 그거 완전 치약맛 아닌가요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-143, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut19', '비도 오고 오늘은 #짬뽕 각이다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-142, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut20', '요즘 #햄버거 만 너무 먹어댔더니 살 쪄가는게 눈에 보이는 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-141, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut21', '#한식 #일식 #양식 뭐먹지 메뉴 정하기 너무 힘들다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-140, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut22', '#데이터베이스 공부중인데 잘 이해가 안되네요 ㅠ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-139, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut23', '어머니는 #짜장면 이 싫다고 하셨어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-138, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut24', '#스마트폰 바꿀 때 된거같은데 #아이폰 #갤럭시 고민된다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-137, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut25', '#넷플릭스 #퀸스갬빗 진짜 재밌어 #체스 하는 사람이면 꼭 봐라 두 번 봐라', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-136, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut26', '#가챠 또 폭사했다. 확률 너무 양심없는거 아닙니까', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-135, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut27', '#라멘 은 역시 #돈코츠라멘 이라 생각했는데 요즘 #츠케멘 에 눈을 뜨게 된 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-134, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut28', '#빅데이터 에 기반해 조사한 결과 당신은 지금 #치킨이 먹고싶습니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-133, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut29', '이 시간만 되면 묘한 두통이 찾아오는데 이유가 뭐지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-132, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut30', '윗집엔 #코끼리 를 키우고 있는게 분명하다 이 세상 #층간소음 이 아니다 진짜', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-131, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut31', '#ajax 배우니까 신세계가 열린 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-130, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut32', '진성 #까르보나라 덕후인 저도 가끔 #토마토파스타 가 더 땡길 때가 있긴 해요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-129, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut33', '#해장 으로 #해장술 마신다는 사람과는 거리를 좀 두는게 좋아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-128, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut34', '#마카롱 선물받은거 냉동실에 넣어놨다 까먹었어; 두 달 지났는데 이거 먹어도 될까요?', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-127, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut35', '못참겠다 #야식 주문 간다 #족발 vs #보쌈 뭐시키지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-126, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut36', '시연용 더미데이터 계획은 다 다른 문장으로 200개 만드는 거였는데 졸려서 못해먹겠다 걍 복붙해야지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-125, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut37', '#Eclipse 만 쓰다가 얼마전에 #IntelliJ 조금씩 써보고 있는데 편한 부분이 많긴 하다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-124, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut38', '벌써 새벽 네시 반이 넘었어 이젠 정말 자야해', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-123, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut39', '정말 애석하게도 내 #고양이 아니고 퍼온 사진입니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-122, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut40', '진짜 완성 못하는줄 알았는데 #프로젝트 마무리가 되긴 됐다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-121, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut1', '#한식 #김치찌개 ㅈㅁㅌ 요즘 #민트초코 에 빠져있다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-120, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut2', '내일 #일식 #초밥 100개 먹방 도전합니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-119, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut3', '#코딩 #자바 공부 시작', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-118, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut4', '#야식 #치킨 #족발 끊을 수가 없네요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-117, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut5', '어제 너무 마셨는데 #해장 으로 뭐먹지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-116, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut6', '오늘도 고민한다 #김치찌개 #된장찌개 #순두부찌개', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-115, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut7', '#해장 엔 역시 #콩나물국밥 만한게 없지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-114, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut8', '자다가 속쓰려서 일어났다...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-113, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut9', '#안동소주 는 참 좋은게 몇잔만 마셔도 적당히 취기가 올라서 현생 스트레스 잊는데 도움이 된다. #소주는 몇 병을 마셔도 취한줄도 모르다 갑자기 훅 가버리는 느낌이야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-112, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut10', '오늘 #생일 인데 축하해주는 사람 하나 없네', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-111, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut11', '나만 #고양이 없어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-110, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut12', '끼요오오옷', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-109, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut13', '#탕수육 부먹했다고 진짜 싸울뻔했네;;', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-108, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut14', '새벽에 이게 뭐하는 짓이야 ㅋㅋ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-107, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut15', '#김밥 에 #오이 들어간 건 참을 수가 없다 대체 왜 넣는거야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-106, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut16', '#파이썬 입문중인데 꿀잼이네. 나 이쪽 적성에 맞나봐요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-105, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut17', '이 시국이 끝나야 #해외여행 도 좀 가고 할텐데...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-104, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut18', '#민트초코 그거 완전 치약맛 아닌가요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-103, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut19', '비도 오고 오늘은 #짬뽕 각이다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-102, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut20', '요즘 #햄버거 만 너무 먹어댔더니 살 쪄가는게 눈에 보이는 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-101, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut21', '#한식 #일식 #양식 뭐먹지 메뉴 정하기 너무 힘들다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-100, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut22', '#데이터베이스 공부중인데 잘 이해가 안되네요 ㅠ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-99, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut23', '어머니는 #짜장면 이 싫다고 하셨어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-98, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut24', '#스마트폰 바꿀 때 된거같은데 #아이폰 #갤럭시 고민된다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-97, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut25', '#넷플릭스 #퀸스갬빗 진짜 재밌어 #체스 하는 사람이면 꼭 봐라 두 번 봐라', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-96, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut26', '#가챠 또 폭사했다. 확률 너무 양심없는거 아닙니까', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-95, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut27', '#라멘 은 역시 #돈코츠라멘 이라 생각했는데 요즘 #츠케멘 에 눈을 뜨게 된 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-94, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut28', '#빅데이터 에 기반해 조사한 결과 당신은 지금 #치킨이 먹고싶습니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-93, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut29', '이 시간만 되면 묘한 두통이 찾아오는데 이유가 뭐지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-92, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut30', '윗집엔 #코끼리 를 키우고 있는게 분명하다 이 세상 #층간소음 이 아니다 진짜', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-91, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut31', '#ajax 배우니까 신세계가 열린 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-90, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut32', '진성 #까르보나라 덕후인 저도 가끔 #토마토파스타 가 더 땡길 때가 있긴 해요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-89, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut33', '#해장 으로 #해장술 마신다는 사람과는 거리를 좀 두는게 좋아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-88, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut34', '#마카롱 선물받은거 냉동실에 넣어놨다 까먹었어; 두 달 지났는데 이거 먹어도 될까요?', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-87, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut35', '못참겠다 #야식 주문 간다 #족발 vs #보쌈 뭐시키지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-86, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut36', '시연용 더미데이터 계획은 다 다른 문장으로 200개 만드는 거였는데 졸려서 못해먹겠다 걍 복붙해야지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-85, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut37', '#Eclipse 만 쓰다가 얼마전에 #IntelliJ 조금씩 써보고 있는데 편한 부분이 많긴 하다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-84, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut38', '벌써 새벽 네시 반이 넘었어 이젠 정말 자야해', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-83, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut39', '정말 애석하게도 내 #고양이 아니고 퍼온 사진입니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-82, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut40', '진짜 완성 못하는줄 알았는데 #프로젝트 마무리가 되긴 됐다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-81, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut1', '#한식 #김치찌개 ㅈㅁㅌ 요즘 #민트초코 에 빠져있다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-80, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut2', '내일 #일식 #초밥 100개 먹방 도전합니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-79, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut3', '#코딩 #자바 공부 시작', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-78, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut4', '#야식 #치킨 #족발 끊을 수가 없네요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-77, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut5', '어제 너무 마셨는데 #해장 으로 뭐먹지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-76, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut6', '오늘도 고민한다 #김치찌개 #된장찌개 #순두부찌개', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-75, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut7', '#해장 엔 역시 #콩나물국밥 만한게 없지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-74, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut8', '자다가 속쓰려서 일어났다...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-73, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut9', '#안동소주 는 참 좋은게 몇잔만 마셔도 적당히 취기가 올라서 현생 스트레스 잊는데 도움이 된다. #소주는 몇 병을 마셔도 취한줄도 모르다 갑자기 훅 가버리는 느낌이야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-72, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut10', '오늘 #생일 인데 축하해주는 사람 하나 없네', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-71, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut11', '나만 #고양이 없어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-70, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut12', '끼요오오옷', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-69, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut13', '#탕수육 부먹했다고 진짜 싸울뻔했네;;', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-68, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut14', '새벽에 이게 뭐하는 짓이야 ㅋㅋ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-67, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut15', '#김밥 에 #오이 들어간 건 참을 수가 없다 대체 왜 넣는거야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-66, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut16', '#파이썬 입문중인데 꿀잼이네. 나 이쪽 적성에 맞나봐요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-65, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut17', '이 시국이 끝나야 #해외여행 도 좀 가고 할텐데...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-64, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut18', '#민트초코 그거 완전 치약맛 아닌가요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-63, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut19', '비도 오고 오늘은 #짬뽕 각이다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-62, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut20', '요즘 #햄버거 만 너무 먹어댔더니 살 쪄가는게 눈에 보이는 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-61, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut21', '#한식 #일식 #양식 뭐먹지 메뉴 정하기 너무 힘들다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-60, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut22', '#데이터베이스 공부중인데 잘 이해가 안되네요 ㅠ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-59, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut23', '어머니는 #짜장면 이 싫다고 하셨어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-58, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut24', '#스마트폰 바꿀 때 된거같은데 #아이폰 #갤럭시 고민된다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-57, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut25', '#넷플릭스 #퀸스갬빗 진짜 재밌어 #체스 하는 사람이면 꼭 봐라 두 번 봐라', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-56, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut26', '#가챠 또 폭사했다. 확률 너무 양심없는거 아닙니까', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-55, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut27', '#라멘 은 역시 #돈코츠라멘 이라 생각했는데 요즘 #츠케멘 에 눈을 뜨게 된 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-54, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut28', '#빅데이터 에 기반해 조사한 결과 당신은 지금 #치킨이 먹고싶습니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-53, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut29', '이 시간만 되면 묘한 두통이 찾아오는데 이유가 뭐지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-52, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut30', '윗집엔 #코끼리 를 키우고 있는게 분명하다 이 세상 #층간소음 이 아니다 진짜', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-51, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut31', '#ajax 배우니까 신세계가 열린 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-50, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut32', '진성 #까르보나라 덕후인 저도 가끔 #토마토파스타 가 더 땡길 때가 있긴 해요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-49, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut33', '#해장 으로 #해장술 마신다는 사람과는 거리를 좀 두는게 좋아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-48, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut34', '#마카롱 선물받은거 냉동실에 넣어놨다 까먹었어; 두 달 지났는데 이거 먹어도 될까요?', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-47, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut35', '못참겠다 #야식 주문 간다 #족발 vs #보쌈 뭐시키지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-46, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut36', '시연용 더미데이터 계획은 다 다른 문장으로 200개 만드는 거였는데 졸려서 못해먹겠다 걍 복붙해야지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-45, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut37', '#Eclipse 만 쓰다가 얼마전에 #IntelliJ 조금씩 써보고 있는데 편한 부분이 많긴 하다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-44, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut38', '벌써 새벽 네시 반이 넘었어 이젠 정말 자야해', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-43, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut39', '정말 애석하게도 내 #고양이 아니고 퍼온 사진입니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-42, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut40', '진짜 완성 못하는줄 알았는데 #프로젝트 마무리가 되긴 됐다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-41, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut1', '#한식 #김치찌개 ㅈㅁㅌ 요즘 #민트초코 에 빠져있다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-40, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut2', '내일 #일식 #초밥 100개 먹방 도전합니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-39, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut3', '#코딩 #자바 공부 시작', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-38, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut4', '#야식 #치킨 #족발 끊을 수가 없네요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-37, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut5', '어제 너무 마셨는데 #해장 으로 뭐먹지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-36, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut6', '오늘도 고민한다 #김치찌개 #된장찌개 #순두부찌개', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-35, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut7', '#해장 엔 역시 #콩나물국밥 만한게 없지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-34, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut8', '자다가 속쓰려서 일어났다...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-33, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut9', '#안동소주 는 참 좋은게 몇잔만 마셔도 적당히 취기가 올라서 현생 스트레스 잊는데 도움이 된다. #소주는 몇 병을 마셔도 취한줄도 모르다 갑자기 훅 가버리는 느낌이야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-32, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut10', '오늘 #생일 인데 축하해주는 사람 하나 없네', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-31, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut11', '나만 #고양이 없어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-30, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut12', '끼요오오옷', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-29, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut13', '#탕수육 부먹했다고 진짜 싸울뻔했네;;', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-28, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut14', '새벽에 이게 뭐하는 짓이야 ㅋㅋ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-27, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut15', '#김밥 에 #오이 들어간 건 참을 수가 없다 대체 왜 넣는거야', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-26, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut16', '#파이썬 입문중인데 꿀잼이네. 나 이쪽 적성에 맞나봐요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-25, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut17', '이 시국이 끝나야 #해외여행 도 좀 가고 할텐데...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-24, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut18', '#민트초코 그거 완전 치약맛 아닌가요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-23, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut19', '비도 오고 오늘은 #짬뽕 각이다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-22, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut20', '요즘 #햄버거 만 너무 먹어댔더니 살 쪄가는게 눈에 보이는 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-21, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut21', '#한식 #일식 #양식 뭐먹지 메뉴 정하기 너무 힘들다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-20, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut22', '#데이터베이스 공부중인데 잘 이해가 안되네요 ㅠ', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-19, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut23', '어머니는 #짜장면 이 싫다고 하셨어', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-18, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut24', '#스마트폰 바꿀 때 된거같은데 #아이폰 #갤럭시 고민된다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-17, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut25', '#넷플릭스 #퀸스갬빗 진짜 재밌어 #체스 하는 사람이면 꼭 봐라 두 번 봐라', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-16, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut26', '#가챠 또 폭사했다. 확률 너무 양심없는거 아닙니까', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-15, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut27', '#라멘 은 역시 #돈코츠라멘 이라 생각했는데 요즘 #츠케멘 에 눈을 뜨게 된 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-14, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut28', '#빅데이터 에 기반해 조사한 결과 당신은 지금 #치킨이 먹고싶습니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-13, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut29', '이 시간만 되면 묘한 두통이 찾아오는데 이유가 뭐지...', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-12, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut30', '윗집엔 #코끼리 를 키우고 있는게 분명하다 이 세상 #층간소음 이 아니다 진짜', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-11, 'n');

insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut31', '#ajax 배우니까 신세계가 열린 것 같아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-10, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut32', '진성 #까르보나라 덕후인 저도 가끔 #토마토파스타 가 더 땡길 때가 있긴 해요', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-9, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut33', '#해장 으로 #해장술 마신다는 사람과는 거리를 좀 두는게 좋아', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-8, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut34', '#마카롱 선물받은거 냉동실에 넣어놨다 까먹었어; 두 달 지났는데 이거 먹어도 될까요?', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-7, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut35', '못참겠다 #야식 주문 간다 #족발 vs #보쌈 뭐시키지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-6, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut36', '시연용 더미데이터 계획은 다 다른 문장으로 200개 만드는 거였는데 졸려서 못해먹겠다 걍 복붙해야지', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-5, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut37', '#Eclipse 만 쓰다가 얼마전에 #IntelliJ 조금씩 써보고 있는데 편한 부분이 많긴 하다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-4, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut38', '벌써 새벽 네시 반이 넘었어 이젠 정말 자야해', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-3, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut39', '정말 애석하게도 내 #고양이 아니고 퍼온 사진입니다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-2, 'n');
insert into pn_peanuts values(peanut_no_seq.nextval, 'pnut40', '진짜 완성 못하는줄 알았는데 #프로젝트 마무리가 되긴 됐다', '0:0:0:0:0:0:0:1', null, null, null, null, null, sysdate-1, 'n');